### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mjholtzem**
Tween callbacks are very helpful, but there are some cases where you may want to add to the callbacks rather than overwrite them.

This change adds additional TweenSettingsExtensions methods for all callbacks to add to them rather than set them.

### CODE REVIEW

**Comment by Demigiant** [comment]
Hi Matt,

I initially didn't want to do this because of various reasons, but I honestly can't remember them very well nowadays. So I'm gonna add it now, but with some minor API changes maybe. Will get back to you as soon as I'm done, and thanks for the contribution :)

**Comment by mjholtzem** [comment]
awesome thanks for taking a look so quick!

**Comment by Demigiant** [comment]
Hey, actually, let's open a small debate within us. I was implementing also an `On[Callback]Remove` method, when I thought... what if I just make the `onStart/Complete/etc` delegates public? That way, one could use the old `On[Callback]` method to add/replace/clear a single callback, and `myTween.on[Callback]` to add more callbacks directly. Do you see any downsides to this?

**Comment by mjholtzem** [comment]
only downside I can think of is that you would not have the ability to add callbacks via method chaining, but the need to do this would probably be VERY rare as you likely would not be adding at the creation of the tween, but after the fact. And if one really wanted this they could add there own extension easily.

**Comment by Demigiant** [comment]
That is true, but I like that you can't method chain multiple callbacks. Both because it shouldn't be seen as something too "quick" to do (because it's usually more efficient to have a single callback that fires multiple methods), nor something too "easy". Ok I'm going for it! :)

**Comment by mjholtzem** [comment]
makes sense, "hiding" it is a good way to say "hey you can do this but it's for advanced users only who understand the implications"

**Comment by Demigiant** [comment]
Absolutely. Aaand I pushed it :) Gonna update the docs and release the ZIP on the website in a short while.

**Comment by Demigiant** [comment]
All updated now :) http://dotween.demigiant.com/download.php

**Pull request closed without merging**
