### PR TITLE
Manuel update feature

### PR DESCRIPTION
**Pull request by sayiliromer**
Hey i added manuel update feature for the project i am working on. I think its a must have feature.

### CODE REVIEW

**Comment by Demigiant** [comment]
Hi Omer,

This is very interesting. Gimme some time to check it and verify both code and API coherency and I'll merge it :)

Cheers,
Daniele

**Comment by Demigiant** [comment]
Hi again,

I just pushed an update that implements your ManualUpdate. Can you give it a go and verify that everything works as intended?

**API CHANGES**
`DOTween.ManualUpdate` instead of `DOTween.ManuelUpdate`
`UpdateType.Manual` instead of `UpdateType.Manuel`

**CODE CHANGES**
It's all almost the same, except I changed some IFs with SWITCHes (I was using IFs to speed things up in case of UpdateType.Normal, which is the most probable, but now that we have more of the other UpdateTypes, I use an IF followed by a SWITCH), and I made the DOTweenComponent.ManualUpdate method internal.

**Comment by Demigiant** [comment]
Oh, and I forgot to mention another code change. Your code wasn't taking into account a tween's timeScale when using ManualUpdate, and I changed that. I don't know if that was by design, but it seems more coherent and interesting to use it.

**Comment by sayiliromer** [comment]
Hey, I updated it with your API changes. It seems working fine , thanks. The manual update feature comes handy when the project architecture is like MVC pattern.  We keep render and simulation separated.

**Comment by Demigiant** [comment]
Great :) Pushed it publicly on the website, and added you to the [credits](http://dotween.demigiant.com/credits.php).

**Pull request closed without merging**
