### PR TITLE
Added material shortcuts

### PR DESCRIPTION
**Pull request by VasylRomanets**
Added material shortcuts that take property ID (int) instead of property name (string). Sorry, I forgot to create a separate branch for my changes :)

### CODE REVIEW

**Comment by Demigiant** [comment]
Cool! :) Gonna merge them asap!

**Comment by dotsquid** [comment]
Hey @Demigiant, so what about approving this PR?

**Comment by Demigiant** [comment]
Ik, I am missing so much stuff *_* Will try to check it out tomorrow and add it along a few other features I'm working on. I bow to you @VasylRomanets

**Comment by VasylRomanets** [comment]
I've noticed the message above 'This branch has conflicts that must be resolved'. So I'll close the PR, resolve conflicts and create another PR.

**Comment by Demigiant** [comment]
You are the bosss! But don't worry, I don't do merges anyway, I just check the code and include it in the dev branch (I feel this is safer), so I can resolve the conflicts directly while I'm including it :)

**Comment by VasylRomanets** [comment]
Thank you @Demigiant!

**Comment by Demigiant** [comment]
No, thank you :) Hey, I also come to say that I got a sudden job for tomorrow that will probably require crunch, so I'll get on this in the weekend :P

**Comment by Demigiant** [comment]
Ahoy! I'm implementing your work right now. If you see conflicts alerts in your branch don't worry, they'll be solved in a short while :)

**Pull request closed without merging**
