### PR TITLE
Added ability to pause a whole Sequence from their callback including other callbacks

### PR DESCRIPTION
**Pull request by DrogerKerchva**
Hey there!

I have added ability to pause a whole ```Sequence``` from their callback including other callbacks. It is very often situation when I have some ```Sequence``` which has several callbacks one by one (added from several ```if``` conditions) and sometimes it is very useful to have an ability to pause ```Sequence``` execution after some callback while delaying rest of callbacks.

Let me show you an example:

```csharp
var sequence = DOTween.Sequence();

sequence.AppendSomething();
sequence.AppendCallback(() => { if (condition) sequence.Pause()});

if(someExpression) sequence.AppendCallback(() => Action1());
```

So as you can see I'm trying to pause a ```sequence``` from one of appended callbacks but ***anyway*** I can see that next callback will be fired.

### CODE REVIEW

**Comment by Demigiant** [comment]
Ahoy!

Thank you for the addition I appreciate it very much :) I think this can be solved without adding a new tween variable though: I'm trying right now.

**Comment by Demigiant** [comment]
Should be fixed :) Could you test [this update](dotween.demigiant.com/tmp/DOTween_1_2_260.zip) to see if it's alright for you too?

In short, the problem wasn't that the Sequence wasn't paused, but that it waited one frame (meaning that I checked if the Sequence was paused before looping through the same-frame tweens/callbacks, and not during it). Now inside the same-frame for-loop I check if the Sequence was paused (by using the existing `tween.isPlaying` property) and stop it immediately.

**Comment by DrogerKerchva** [comment]
@Demigiant Hi!

I tested your fix and it seems to produce exact result I tried to achieve

**Comment by Demigiant** [comment]
Great! Will push this in the next update as long as a few other things. And thank you again :)

**Pull request closed without merging**
